### ISSUE TITLE
Reconsider CC-ND?

### ISSUE THREAD

**Issue by Steve-V** [jackmorgan/the-plain-contract#2]
The Creative Commons license chosen for this contract is CC-BY-NC-ND-4.0. It is a license which prohibits works from being redistributed after being modified.

    NoDerivatives - If you remix, transform, or build upon the material, you may not distribute the modified material.

If I remix the contract by filling in the form fields, does that prohibit me from distributing it to my clients?

**Comment by jackmorgan** [comment]
License updated to CC BY-SA 4.0. Thanks, Steve.
